# Site settings
# Site title
title: 9th Circle Games // Brand New Worlds

# Site description
description: "Indie game design studio specializzato in giochi di ruolo e di narrazione. Autori del pluripremiato RPG \"Eden: l'Inganno\""

# Site background
background: "images/background.jpg"

# Site logo
logo: "images/logo.png"

# Countdown clock
# (This can be commented out if not required.)
#countdown:
  # format: "2013-09-25 16:00:00 +0800"
#  launch_date: 2020-01-01
  # %d, %H, %M, %S available
#  format: "%d days, %H hours, %M minutes, %S seconds"

# Mailing list subscription
# (This can be commented out if not required.)
subscribe:
  action: ""


# Social media links
# (This can be commented out if not required.)
social:
  facebook: "9thcirclegames"
#  twitter: "#"
#  google: "#"
#  instagram: "#"
#  pinterest: "#"
#  snapchat: "#"
  linkedin: "company/9th-circle-games/"

# Build settings
markdown: kramdown

url : "https://9thcircle.it"
baseurl : "/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - README.md
   - COPYING.txt
